apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: deploy-nginx
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: deploy-nginx-pod
  template:
    metadata:
      labels:
        app: deploy-nginx-pod 
    spec:
      containers:
      - name: deploy-nginx
        image: nginx:1.21.6
        resources:
          limits:
            memory: "128Mi"
            cpu: "1"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: deploy-nginx-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: deploy-nginx-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31260
    
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: deploy-nginx-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-nginx
  maxReplicas: 10
  minReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageUtilization: 90
        type: Value
